In [1]:
import pandas as pd
pd.options.display.max_columns = 500
pd.options.display.max_rows = 100

### Sales

In [11]:
sales = pd.read_csv('vgsales.csv')
print(sales['Name'].nunique())
sales.shape

11493

(16598, 11)

In [25]:
sales.head(10)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37
5,6,Tetris,GB,1989.0,Puzzle,Nintendo,23.20,2.26,4.22,0.58,30.26
6,7,New Super Mario Bros.,DS,2006.0,Platform,Nintendo,11.38,9.23,6.50,2.90,30.01
7,8,Wii Play,Wii,2006.0,Misc,Nintendo,14.03,9.20,2.93,2.85,29.02
8,9,New Super Mario Bros. Wii,Wii,2009.0,Platform,Nintendo,14.59,7.06,4.70,2.26,28.62
9,10,Duck Hunt,NES,1984.0,Shooter,Nintendo,26.93,0.63,0.28,0.47,28.31

In [31]:
sales[sales['Year'] >= 2016.0]

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
221,222,FIFA 17,PS4,2016.0,Sports,Electronic Arts,0.28,3.75,0.06,0.69,4.77
271,272,Uncharted 4: A Thief's End,PS4,2016.0,Shooter,Sony Computer Entertainment,1.30,2.07,0.18,0.65,4.20
351,352,Tom Clancy's The Division,PS4,2016.0,Shooter,Ubisoft,1.28,1.61,0.15,0.57,3.61
770,772,Far Cry: Primal,PS4,2016.0,Action,Ubisoft,0.59,1.16,0.06,0.33,2.13
845,847,Tom Clancy's The Division,XOne,2016.0,Shooter,Ubisoft,1.20,0.62,0.00,0.18,2.01
...,...,...,...,...,...,...,...,...,...,...,...
16562,16565,Mighty No. 9,XOne,2016.0,Platform,Deep Silver,0.01,0.00,0.00,0.00,0.01
16569,16572,Resident Evil 4 HD,XOne,2016.0,Shooter,Capcom,0.01,0.00,0.00,0.00,0.01
16570,16573,Farming 2017 - The Simulation,PS4,2016.0,Simulation,UIG Entertainment,0.00,0.01,0.00,0.00,0.01
16576,16579,Rugby Challenge 3,XOne,2016.0,Sports,Alternative Software,0.00,0.01,0.00,0.00,0.01
16589,16592,Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...,PSV,2016.0,Action,dramatic create,0.00,0.00,0.01,0.00,0.01

In [12]:
url = pd.read_csv('vgsales_url.csv')
print(url['Name'].nunique())
url.head()

37102

,Rank,Name,basename,Genre,ESRB_Rating,Platform,Publisher,Developer,VGChartz_Score,Critic_Score,User_Score,Total_Shipped,Global_Sales,NA_Sales,PAL_Sales,JP_Sales,Other_Sales,Year,Last_Update,url,status,Vgchartzscore,img_url
0,1,Wii Sports,wii-sports,Sports,E,Wii,Nintendo,Nintendo EAD,NaN,7.7,NaN,82.86,NaN,NaN,NaN,NaN,NaN,2006.0,NaN,http://www.vgchartz.com/game/2667/wii-sports/?...,1,NaN,/games/boxart/full_2258645AmericaFrontccc.jpg
1,2,Super Mario Bros.,super-mario-bros,Platform,NaN,NES,Nintendo,Nintendo EAD,NaN,10.0,NaN,40.24,NaN,NaN,NaN,NaN,NaN,1985.0,NaN,http://www.vgchartz.com/game/6455/super-mario-...,1,NaN,/games/boxart/8972270ccc.jpg
2,3,Mario Kart Wii,mario-kart-wii,Racing,E,Wii,Nintendo,Nintendo EAD,NaN,8.2,9.1,37.14,NaN,NaN,NaN,NaN,NaN,2008.0,11th Apr 18,http://www.vgchartz.com/game/6968/mario-kart-w...,1,8.7,/games/boxart/full_8932480AmericaFrontccc.jpg
3,4,PlayerUnknown's Battlegrounds,playerunknowns-battlegrounds,Shooter,NaN,PC,PUBG Corporation,PUBG Corporation,NaN,NaN,NaN,36.60,NaN,NaN,NaN,NaN,NaN,2017.0,13th Nov 18,http://www.vgchartz.com/game/215988/playerunkn...,1,NaN,/games/boxart/full_8052843AmericaFrontccc.jpg
4,5,Wii Sports Resort,wii-sports-resort,Sports,E,Wii,Nintendo,Nintendo EAD,NaN,8.0,8.8,33.09,NaN,NaN,NaN,NaN,NaN,2009.0,NaN,http://www.vgchartz.com/game/24656/wii-sports-...,1,8.8,/games/boxart/full_7295041AmericaFrontccc.jpg

In [33]:
url[url['Year'] >= 2017.0].head()

,Rank,Name,basename,Genre,ESRB_Rating,Platform,Publisher,Developer,VGChartz_Score,Critic_Score,User_Score,Total_Shipped,Global_Sales,NA_Sales,PAL_Sales,JP_Sales,Other_Sales,Year,Last_Update,url,status,Vgchartzscore,img_url
3,4,PlayerUnknown's Battlegrounds,playerunknowns-battlegrounds,Shooter,NaN,PC,PUBG Corporation,PUBG Corporation,NaN,NaN,NaN,36.60,NaN,NaN,NaN,NaN,NaN,2017.0,13th Nov 18,http://www.vgchartz.com/game/215988/playerunkn...,1,NaN,/games/boxart/full_8052843AmericaFrontccc.jpg
35,36,Mario Kart 8 Deluxe,mario-kart-8-deluxe,Racing,E,NS,Nintendo,Nintendo EPD,NaN,9.3,NaN,15.02,NaN,NaN,NaN,NaN,NaN,2017.0,19th Nov 18,http://www.vgchartz.com/game/153114/mario-kart...,1,NaN,/games/boxart/full_895207AmericaFrontccc.png
45,46,Red Dead Redemption 2,red-dead-redemption-2,Action-Adventure,M,PS4,Rockstar Games,Rockstar Games,NaN,9.8,NaN,NaN,13.94,5.26,6.21,0.21,2.26,2018.0,02nd Nov 18,http://www.vgchartz.com/game/140683/red-dead-r...,1,8.0,/games/boxart/full_4653215AmericaFrontccc.jpg
48,49,Super Mario Odyssey,super-mario-odyssey,Platform,E10,NS,Nintendo,Nintendo EPD,NaN,9.9,NaN,13.76,NaN,NaN,NaN,NaN,NaN,2017.0,19th Nov 18,http://www.vgchartz.com/game/152831/super-mari...,1,NaN,/games/boxart/full_1659701AmericaFrontccc.jpg
50,51,Call of Duty: WWII,call-of-duty-wwii,Shooter,M,PS4,Activision,Sledgehammer Games,NaN,8.0,NaN,NaN,13.40,4.67,6.21,0.40,2.12,2017.0,31st Dec 17,http://www.vgchartz.com/game/170599/call-of-du...,1,NaN,/games/boxart/full_4380292AmericaFrontccc.jpg

### user

In [5]:
user = pd.read_csv('user_games.csv')
user.columns = ['user_id','game','action','time','0']

In [6]:
user.shape

(199999, 5)

In [7]:
user.head()

     user_id                        game    action   time  0
0  151603712  The Elder Scrolls V Skyrim      play  273.0  0
1  151603712                   Fallout 4  purchase    1.0  0
2  151603712                   Fallout 4      play   87.0  0
3  151603712                       Spore  purchase    1.0  0
4  151603712                       Spore      play   14.9  0

In [8]:
user['game'].nunique()

5155

In [21]:
user.sort_values(by='time', ascending = False).head()

          user_id                        game action     time  0
123725   73017395  Sid Meier's Civilization V   play  11754.0  0
112642  100630947                      Dota 2   play  10442.0  0
187004  153382649             Team Fortress 2   play   9640.0  0
165595  130882834                      Dota 2   play   7765.0  0
183460   52567955                      Dota 2   play   6964.0  0

### Steam games

In [9]:
steam = pd.read_csv('steamgames.csv')

In [10]:
print(steam.shape)
print(steam['steamid'].nunique())

(1504, 19)
96

In [12]:
steam.head()

,week,steamid,owner_base,average_price,pre_average_price,action,adventure,casual,puzzle,RPG,sports,simulation,strategy,new_followers,peak_concurrent,sharing_percentage,average_playtime,covid_confirmed,owners_change
0,1,359550,16390000,16.56,7.99,1,0,1,0,0,0,0,1,2516,117930,24.77,613,0,449000
1,2,359550,16839000,19.99,16.56,1,0,1,0,0,0,0,1,2123,106261,25.78,686,0,467000
2,3,359550,17306000,19.99,19.99,1,0,1,0,0,0,0,1,2351,125478,24.95,611,0,-234000
3,4,359550,17072000,14.85,19.99,1,0,1,0,0,0,0,1,3170,131110,22.67,710,14207,-464000
4,5,359550,16608000,19.99,14.85,1,0,1,0,0,0,0,1,2188,124493,23.91,800,96925,299000

In [20]:
steam.sort_values(by='average_playtime', ascending = False).head()

,week,steamid,owner_base,average_price,pre_average_price,action,adventure,casual,puzzle,RPG,sports,simulation,strategy,new_followers,peak_concurrent,sharing_percentage,average_playtime,covid_confirmed,owners_change
1360,1,629910,217000,28.53,19.79,1,1,1,0,1,0,1,1,-9,208,0.00,20101,0,6000
235,1,724970,272000,29.99,29.99,0,0,0,0,1,0,0,0,16,20,0.00,16521,0,-2000
236,2,724970,270000,29.99,29.99,0,0,0,0,1,0,0,0,9,24,7.14,14555,0,-16000
1361,2,629910,223000,29.99,28.53,1,1,1,0,1,0,1,1,-2,159,28.57,6225,0,10000
1280,1,414700,846000,23.56,7.49,1,1,0,0,0,0,0,0,46,239,1.44,5470,0,-429000

### Playtimes

In [2]:
playtime = pd.read_csv('playtimes.csv')

In [13]:
print(playtime['name'].nunique())
print(playtime.shape)
playtime.head()

17696
(17772, 47)

,all_styles_duration_average,all_styles_duration_leisure,all_styles_duration_median,all_styles_duration_rushed,all_styles_duration_submissions,any_percent_speedrun_duration_average,any_percent_speedrun_duration_fastest,any_percent_speedrun_duration_median,any_percent_speedrun_duration_polled,any_percent_speedrun_duration_slowest,backlogs,beat,completionist_duration_average,completionist_duration_leisure,completionist_duration_median,completionist_duration_rushed,completionist_duration_submissions,description,developer,game_type,genres,last_updated,launch_dates,main_story_duration_average,main_story_duration_leisure,main_story_duration_median,main_story_duration_rushed,main_story_duration_submissions,main_story_plus_extras_duration_average,main_story_plus_extras_duration_leisure,main_story_plus_extras_duration_median,main_story_plus_extras_duration_rushed,main_story_plus_extras_duration_submissions,name,one_hundred_percent_speedrun_duration_average,one_hundred_percent_speedrun_duration_fastest,one_hundred_percent_speedrun_duration_median,one_hundred_percent_speedrun_duration_polled,one_hundred_percent_speedrun_duration_slowest,platforms,playing,publisher,rating,replays,retired,submissions_per_platform,website_id
0,4h 53m,7h 44m,4h 05m,3h 34m,16.0,NaN,NaN,NaN,NaN,NaN,NaN,38.0,11h,11h,11h,11h,1.0,25 To Life is third-person shooter action set...,"Avalanche Software, Ritual Entertainment",game,Third-person shooter,1.5 Hours Ago,NaN,4h 34m,6h 17m,4h 05m,3h 30m,12.0,4h 07m,4h 19m,4h,3h 55m,3.0,25 To Life,NaN,NaN,NaN,NaN,NaN,"PC, PlayStation 2, Xbox",0.0,Eidos Interactive,57.0,1.0,2,"PC:6,PlayStation 2:7,Xbox:3",62
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0,1h 07m,2h 31m,35m,38m,7.0,19XX: The War Against Destiny takes place dur...,Capcom,game,"Scrolling, Shooter",2.5 Months Ago,NaN,37m,47m,34m,30m,6.0,4h 12m,4h 12m,4h 12m,4h 12m,1.0,19XX: The War Against Destiny,NaN,NaN,NaN,NaN,NaN,"Arcade,",0.0,Capcom,65.0,1.0,0,Arcade:7,59
2,3h 12m,5h 21m,2h 15m,1h 51m,8.0,NaN,NaN,NaN,NaN,NaN,NaN,23.0,2h,2h,2h,2h,1.0,"Set in the Pacific theater of World War II, o...",Capcom,game,"Top-Down, Scrolling, Arcade",5.5 Days Ago,NaN,3h 39m,5h 33m,2h 32m,2h 03m,6.0,1h 41m,1h 41m,1h 41m,1h 41m,1.0,1943: The Battle of Midway,NaN,NaN,NaN,NaN,NaN,NES,3.0,Capcom,60.0,1.0,5,NES:5,56
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0,NaN,NaN,NaN,NaN,NaN,"Based on the action-packed television series,...",SCE Studio Cambridge,game,Third-person shooter,1 Month Ago,NaN,11h 01m,12h 30m,11h,9h 37m,8.0,11h 01m,12h 30m,11h,9h 37m,8.0,24: The Game,NaN,NaN,NaN,NaN,NaN,PlayStation 2,0.0,"2K Games, Sony Computer Entertainment",61.0,0.0,1,PlayStation 2:8,61
4,14h 45m,23h 41m,10h,9h 11m,9.0,NaN,NaN,NaN,NaN,NaN,NaN,45.0,35h,35h,35h,35h,1.0,With 2010 FIFA World Cup EA Sports celebrates...,"EA Canada, HB Studios",game,Sports,1.5 Weeks Ago,NaN,9h 38m,13h 54m,8h,7h 24m,6.0,20h,20h,20h,20h,2.0,2010 FIFA World Cup South Africa,NaN,NaN,NaN,NaN,NaN,"PlayStation 3, Wii, Xbox 360",5.0,EA Sports,70.0,6.0,11,"PlayStation 3:1,Wii:4,Xbox 360:3",60

In [17]:
playtime['replays'].value_counts()

0.0      10946
1.0       2337
2.0        999
3.0        595
4.0        417
         ...
885.0        1
225.0        1
124.0        1
367.0        1
273.0        1
Name: replays, Length: 234, dtype: int64

### Ratings

In [14]:
ratings = pd.read_csv('ratings.csv')

In [15]:
ratings.head()

,id,game,platform,website_rating,user_rating,release,developer,classification,preview,url
0,1,¡Has sido tú!,PS4,7.5,7.69,4/7/2017,Wish Studios & Sony,PEGI +12,La razón por la que han existido las consolas ...,https://vandal.elespanol.com/analisis/ps4/has-...
1,2,#IDARB,Xbox One,8.2,7,3/2/2015,Other Ocean Interactive,PEGI +3,"Es un fenómeno curioso, pero bien podríamos de...",https://vandal.elespanol.com/analisis/xbone/id...
2,3,007 Racing,PS One,6.9,4.88,Enero 2001,EA Games & Electronic Arts,None,"Bond, James BondCon la reciente tirada de títu...",https://vandal.elespanol.com/analisis/psx/007-...
3,4,007: Agente en Fuego Cruzado,GameCube,7.7,6.3,Año 2002,EA Games & Electronic Arts,None,"No podía ser de otra maneraBond vuelve, no pod...",https://vandal.elespanol.com/analisis/gcn/007-...
4,5,007: Nightfire,GameCube,8.7,6.93,29/11/2002,Eurocom & EA Games,None,Licencia para matarAunque son muchos los jueg...,https://vandal.elespanol.com/analisis/gcn/007-...

In [ ]:
print(ratings.shape)
ratings['']